### ISSUE TITLE
the data file of dg_dict.txt for the datasets are both missing

### ISSUE THREAD

**Issue by ZeroerWiser** [xt-55/GTRL#2]

**Comment by ZeroerWiser** [comment]
as the title shown

**Comment by zhangzhaoxia** [comment]
I would like to ask the author how to solve this problem, looking forward to your answer，thanks！

Traceback (most recent call last):
  File "train_event_predictor.py", line 106, in <module>
    args.dp, args.dataset, num_nodes, num_rels, set_name='train')
  File "E:\PycharmProjects\PycharmProjects\GTRL-main\GTRL-main\GTRL\src\data.py", line 13, in __init__
    data, times = utils.load_quadruples(path + dataset, set_name + '.txt')
ValueError: too many values to unpack (expected 2)

**Comment by ZeroerWiser** [comment]
@zhangzhaoxia  等号右边输出的是三个变量，你可以通过print()的方式去看这些变量代表什么。我看到它第三个输出的是字典，所以等号左边加多一个data_dict就行，反正这个变量后面也不需要

**Comment by zhangzhaoxia** [comment]
问题已解决，学到了通过print方式打印变量，谢谢！ 
FileNotFoundError: [Errno 2] No such file or directory: '../data/example/dg_dict.txt'这个文件丢失了吗？可以直接注释掉吗？

**Comment by likunlin6** [comment]
I have the same question, please answer it, thanks!!!!!

**Comment by zhangzhaoxia** [comment]
> 

找到解决办法了吗

**Comment by likunlin6** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by likunlin6** [comment]
还没有，我对这方面不太了，只能等着作者解决。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xt-55/GTRL"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月23日(星期天) 下午4:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xt-55/GTRL] the data file of dg_dict.txt for the datasets are both missing (Issue #2)





   
找到解决办法了吗
